name: "Hello actions"

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say "Hello
        run: echo "Hi"

      - name: Linux distro
        run: uname -a

      - name: current dir
        run: pwd

      - name: list files
        run: ls -la