name: multi job

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs: 
      image_tag: ${{ steps.build_tag.outputs.image_tag }}
      
    steps:
      - name: build
        id: build_tag
        run: echo "image_tag=abc123" >> "$GITHUB_OUTPUT" 

      - name: create artifact
        run: echo "random bullshit go" >> hellyeah.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifactTM
          path: hellyeah.txt


  test:
    needs: build
    runs-on: ubuntu-latest
    environment: SECRET_ENV

    outputs:
      image_tag: ${{ needs.build.outputs.image_tag }}

    steps:
      - name: print stuff 
        run: echo "testing rn"

      - name: download artifact
        uses: actions/download-artifact@v4
        with: 
          name: artifactTM

      - name: read artifact
        run: cat hellyeah.txt

      - name: echo secret
        run: echo "secret api = ${{ secrets.API_KEY }}"

  deploy:
    if: ${{ github.ref == 'refs/heads/main' && sucess() }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying ${{ needs.test.outputs.image_tag}}"